version: "3"

services:

  web:
    image: "nginx:latest"
    ports:
      - "8080:80"
    build:
      context: ../
      dockerfile: "docker/web/Dockerfile"
    volumes:
      - "../app:/var/www/html"

  php:
    container_name: "php"
    build:
      context: ../
      dockerfile: "docker/php/Dockerfile"
    volumes:
      - "../app:/var/www/html"

  mysql:
    container_name: "mysql"
    build:
      context: ../
      dockerfile: "docker/mysql/Dockerfile"
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=seasonings"
      - "MYSQL_USER=user"
      - "MYSQL_PASSWORD=pass"
    volumes:
      - "mysqldata:/var/lib/mysql"

volumes:
  mysqldata: